apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftm-dev

resources:
- namespace.yaml
- ../../base

# Patches để customize cho dev environment
patchesStrategicMerge:
- replicas-patch.yaml
- ingress-patch.yaml
- configmap-patch.yaml

# Jenkins sẽ update image tags này
images:
- name: acrftmbackenddev.azurecr.io/ftm-backend
  newName: acrftmbackenddev.azurecr.io/ftm-backend
  newTag: v1.0.14
- name: acrftmfrontenddev.azurecr.io/ftm-frontend
  newName: acrftmfrontenddev.azurecr.io/ftm-frontend
  newTag: v1.0.3

commonLabels:
  environment: dev
